# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:01
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.PositiveSmallIntegerField(verbose_name='order')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['program'])),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
                'ordering': ('ind',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.PositiveSmallIntegerField(verbose_name='order')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('note', models.TextField(blank=True, default='', verbose_name='note')),
                ('video', models.URLField(blank=True, default='', verbose_name='video')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['day'])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.Day')),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'ordering': ('ind',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['owner'])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.PositiveSmallIntegerField(verbose_name='order')),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='reps')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='core.Exercise')),
            ],
            options={
                'verbose_name': 'set',
                'verbose_name_plural': 'sets',
                'ordering': ('ind',),
            },
        ),
        migrations.AddField(
            model_name='day',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.Program'),
        ),
        migrations.AlterUniqueTogether(
            name='set',
            unique_together=set([('exercise', 'ind')]),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([('owner', 'title')]),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set([('day', 'title'), ('day', 'ind')]),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together=set([('program', 'ind'), ('program', 'title')]),
        ),
    ]
