version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=backend

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=backend
      - USE_DOCKER=yes
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    links:
      - postgres

  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=backend
    volumes:
      - ./backend:/app
    links:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile-dev
    command: /start-dev.sh
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/app
    environment:
    - NODE_ENV=dev
